apiVersion: apps/v1
kind: Deployment
metadata:
  name: netshoot-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: netshoot
  template:
    metadata:
      labels:
        app: netshoot
    spec:
      containers:
      - name: netshoot-container
        image: nicolaka/netshoot:latest
        command: ["/bin/sleep", "infinity"]  # เพื่อให้ container ทำงานและไม่จบการทำงาน

---
apiVersion: v1
kind: Service
metadata:
  name: netshoot-service
spec:
  selector:
    app: netshoot
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
