apiVersion: apps/v1
kind: Deployment
metadata:
  name: video-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: video
  template:
    metadata:
      labels:
        app: video
    spec:
      containers:
      - name: video
        image: treepaech/ex1-video
        ports:
        - containerPort: 4000  # Change the containerPort to match the exposed port of the application
