FROM rabbitmq:3.12.4-management

EXPOSE 5672 15672

# Optionally, you can specify the port mappings when running the container
# using the -p option with docker run, for example:
# docker run -p 5672:5672 -p 15672:15672 <your_image_name>

